//
//  MachineHomeRouter.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MachineHomeRoutingLogic
{
    func routeToDetail(machineId: String)
}

protocol MachineHomeDataPassing
{
  var dataStore: MachineHomeDataStore? { get }
}

class MachineHomeRouter: NSObject, MachineHomeRoutingLogic, MachineHomeDataPassing
{
  weak var viewController: MachineHomeViewController?
  var dataStore: MachineHomeDataStore?
  
  // MARK: Routing
  
    func routeToDetail(machineId: String)
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MachineDetail") as! MachineDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(destination: &destinationDS, machineId: machineId)
        navigateToDetail(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToDetail(source: MachineHomeViewController, destination: MachineDetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetail(destination: inout MachineDetailDataStore, machineId: String)
    {
        destination.machineId = machineId
        destination.displayMode = "view"
    }
}
