//
//  MachineHomePresenter.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MachineHomePresentationLogic
{
  func presentScannedData(machineId: String, QRCode: String)
}

class MachineHomePresenter: MachineHomePresentationLogic
{
  weak var viewController: MachineHomeDisplayLogic?
  
  // MARK: Do something
  
  func presentScannedData(machineId: String, QRCode: String)
  {
    viewController?.displayScannedData(machineId: machineId, QRCode: QRCode)
  }
}
