//
//  MachineHomePresenter.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MachineHomePresentationLogic
{
  func presentSomething(response: MachineHome.Something.Response)
}

class MachineHomePresenter: MachineHomePresentationLogic
{
  weak var viewController: MachineHomeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MachineHome.Something.Response)
  {
    let viewModel = MachineHome.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
