//
//  MachineDataWorker.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MachineDataWorker
{
  func getList() -> [Machine]
  {
    var machines = [Machine]()
    if let data = UserDefaults.standard.data(forKey: "machines") {
        machines = try! PropertyListDecoder().decode([Machine].self, from: data)
    }
    return machines
  }
}
