//
//  MachineDataPresenter.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// Sent From Interactor
protocol MachineDataPresentationLogic
{
  func presentSomething(machines: [Machine])
}

class MachineDataPresenter: MachineDataPresentationLogic
{
  weak var viewController: MachineDataDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(machines: [Machine])
  {
    viewController?.displaySomething(machines: machines)
  }
}
