//
//  MachineDataModels.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MachineData
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        var machineId: String!
        var machineName: String!
        var machineType: String!
        var QRCodeNumber: String!
        var lastMaintenanceDate: Date!
        var images: [UIImage]?
    }
  }
}
