//
//  MachineDetailPresenter.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MachineDetailPresentationLogic
{
  func presentSomething(machine: Machine)
}

class MachineDetailPresenter: MachineDetailPresentationLogic
{
  weak var viewController: MachineDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(machine: Machine)
  {
    let viewModel = MachineDetail.Something.ViewModel()
    viewController?.displaySomething(machine: machine)
  }
}
