//
//  MachineDetailViewController.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Eureka
import TLPhotoPicker
import Photos

protocol MachineDetailDisplayLogic: class
{
    func displayMachine(machine: Machine)
    func actionCompletedAndLeave()
    func actionFailed(message: String)
}

class MachineDetailViewController: FormViewController, MachineDetailDisplayLogic, TLPhotosPickerViewControllerDelegate
{
    
    var interactor: MachineDetailBusinessLogic?
    var router: (NSObjectProtocol & MachineDetailRoutingLogic & MachineDetailDataPassing)?
    
    var machineId: String!
    var displayMode: String?
    var machine: Machine!
    var needReload: Bool = false
    var photoAssets = [String]()
    
    @IBOutlet weak var trashButton: UIBarButtonItem!
    @IBOutlet weak var rightNavButton: UIBarButtonItem!
    @IBOutlet weak var saveButton: UIBarButtonItem!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = MachineDetailInteractor()
        let presenter = MachineDetailPresenter()
        let router = MachineDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.setupDisplay()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        if displayMode! == "view" && needReload == true {
            interactor?.fetchMachine(machineId: machineId)
        }
    }
    
    // MARK: - Main functions
    
    func setupDisplay() {
        machineId = (router?.dataStore?.machineId)!
        displayMode = (router?.dataStore?.displayMode)!
        self.navigationItem.rightBarButtonItems = nil
        if ((displayMode != nil) && (displayMode! == "edit" ||  displayMode! == "add")) {
            self.navigationItem.rightBarButtonItem = saveButton
            if displayMode! == "add" {
                setupEurekaForm()
                return
            }
        } else {
            self.navigationItem.rightBarButtonItem = nil
            self.navigationItem.rightBarButtonItems = [trashButton, rightNavButton]
        }
        interactor?.fetchMachine(machineId: machineId)
    }
    
    // MARK: - Right Nav action button
    
    @IBAction func rightNavButtonTapped(_ sender: UIBarButtonItem) {
        self.view.endEditing(true)
        if sender == saveButton {
            if displayMode == "add" {
                self.addMachine()
            } else {
                self.editMachine()
            }
        } else {
            needReload = true
            router?.routeToEdit(machineId: machineId)
        }
    }
    
    // MARK: - CRUD Machine
    
    func checkValidity() -> Bool {
        if form.validate().count > 0 {
            let alert = UIAlertController(title: "Whoops", message: "Please fill up all fields", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            return false
        }
        let carousel = form.rowBy(tag: "images") as! CarouselRow
        if carousel.Images.count < 1 {
            let alert = UIAlertController(title: "Whoops", message: "Please attach at least one image", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            return false
        }
        return true
    }
    
    func prepareMachineForAction() -> Machine {
        let values = form.values()
        let carousel = form.rowBy(tag: "images") as! CarouselRow
        let newMachine = Machine(machineId: values["machineId"] as! String, machineName: values["machineName"] as! String, machineType: values["machineType"] as! String, QRCodeNumber: "\(values["QRCodeNumber"] as! Int)", lastMaintenanceDate: values["LastMaintenanceDate"] as! Date, images: carousel.Images)
        return newMachine
    }
    
    func addMachine() {
        guard self.checkValidity() == true else { return }
        let newMachine = self.prepareMachineForAction()
        interactor?.addMachine(newMachine: newMachine)
    }
    
    func editMachine() {
        guard self.checkValidity() == true else { return }
        let editedMachine = self.prepareMachineForAction()
        interactor?.updateMachine(machine: editedMachine)
    }
    
    @IBAction func deleteMachine(_ sender: UIBarButtonItem) {
        interactor?.removeMachine(machineId: machineId)
    }
    
    func actionCompletedAndLeave() {
        self.navigationController?.popViewController(animated: true)
    }
    
    func actionFailed(message: String) {
        let alert = UIAlertController(title: message, message: nil, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
    
    func displayMachine(machine: Machine)
    {
        self.machine = machine
        self.photoAssets = self.machine.images
        if needReload == false {
            if ((displayMode != nil) && (displayMode! == "edit")) {
                self.setupEurekaForm()
            } else {
                self.setupEurekaDisplay()
            }
        } else {
            form.removeAll()
            self.setupEurekaDisplay()
        }
    }
    
    // MARK: - Eureka Form setup
    
    func setupEurekaForm()
    {
        
        form +++ Section("About Machine")
            <<< TextRow(){ row in
                row.title = "Id"
                row.placeholder = "Enter text here"
                if (displayMode! == "add") {
                    row.value = UUID().uuidString
                } else {
                    row.value = machine.machineId
                }
                row.disabled = true
                row.tag = "machineId"
            }
            <<< TextRow(){ row in
                row.title = "Name"
                row.placeholder = "Enter text here"
                if (displayMode! == "edit") {
                    row.value = machine.machineName
                }
                row.tag = "machineName"
                row.add(rule: RuleRequired())
                row.validationOptions = .validatesAlways
            }
            <<< TextRow(){ row in
                row.title = "Type"
                row.placeholder = "Enter text here"
                if (displayMode! == "edit") {
                    row.value = machine.machineType
                }
                row.tag = "machineType"
                row.add(rule: RuleRequired())
                row.validationOptions = .validatesAlways
            }
            <<< IntRow(){
                $0.title = "QRCode No."
                $0.placeholder = "And numbers here"
                if (displayMode! == "edit") {
                    $0.value = Int(machine.QRCodeNumber)
                }
                $0.tag = "QRCodeNumber"
                $0.add(rule: RuleRequired())
                $0.validationOptions = .validatesAlways
            }
            <<< DateTimeRow() {
                $0.title = "Last Maintenance"
                if (displayMode! == "edit") {
                    $0.value = machine.lastMaintenanceDate
                } else {
                    $0.value = Date()
                }
                $0.tag = "LastMaintenanceDate"
                $0.add(rule: RuleRequired())
                $0.validationOptions = .validatesAlways
            }
            +++ Section("Images") {
                $0.tag = "Images"
            }
            <<< CarouselRow(){
                $0.addButtonTarget = self
                $0.addButtonAction = #selector(openImagePicker)
                $0.isEditingMode = true
                if (displayMode! == "edit") {
                    $0.Images = self.photoAssets
                } else {
                    $0.Images = self.photoAssets
                }
                $0.tag = "images"
        }
    }
    
    func setupEurekaDisplay()
    {
        form +++ Section("Machine Id")
            <<< LongTextRow() {
                $0.text = machine.machineId
            }
            +++ Section("Machine Name")
            <<< LongTextRow() {
                $0.text = machine.machineName
            }
            +++ Section("Machine Type")
            <<< LongTextRow() {
                $0.text = machine.machineType
            }
            +++ Section("QRCode Number")
            <<< LongTextRow() {
                $0.text = machine.QRCodeNumber
            }
            +++ Section("Last Maintenance")
            <<< LongTextRow() {
                $0.text = DateFormatter.localizedString(from: machine.lastMaintenanceDate, dateStyle: .short, timeStyle: .short)
            }
            +++ Section("Images") {
                $0.tag = "Images"
            }
            <<< CarouselRow(){
                $0.isEditingMode = false
                $0.Images = machine.images
        }
    }
    
    // MARK: - Photo picker stuffs and delegate
    
    @objc func openImagePicker() {
        let viewController = TLPhotosPickerViewController()
        viewController.delegate = self
        var configure = TLPhotosPickerConfigure()
        configure.allowedLivePhotos = false
        configure.allowedVideo = false
        configure.allowedVideoRecording = false
        configure.maxSelectedAssets = 10 - self.photoAssets.count
        viewController.configure = configure
        self.present(viewController, animated: true, completion: nil)
    }
    
    func dismissPhotoPicker(withPHAssets: [PHAsset]) {
        // if you want to used phasset.
        let carousel = form.rowBy(tag: "images") as! CarouselRow
        self.photoAssets = carousel.Images
        for anAsset in withPHAssets {
            if !self.photoAssets.contains(anAsset.localIdentifier) {
                self.photoAssets.append(anAsset.localIdentifier)
            }
        }
        if let section = form.sectionBy(tag: "Images") as Section? {
            form.remove(at: section.index!)
            form
                +++ Section("Images") {
                    $0.tag = "Images"
                }
                <<< CarouselRow(){
                    $0.addButtonTarget = self
                    $0.addButtonAction = #selector(openImagePicker)
                    $0.isEditingMode = true
                    if (displayMode! == "edit") {
                        $0.Images = self.photoAssets
                    } else {
                        $0.Images = self.photoAssets
                    }
                    $0.tag = "images"
            }
        }
    }
    
    func canSelectAsset(phAsset: PHAsset) -> Bool {
        let carousel = form.rowBy(tag: "images") as! CarouselRow
        return (carousel.Images.contains(phAsset.localIdentifier)) ? false : true
    }
}
