//
//  MachineDetailInteractor.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MachineDetailBusinessLogic
{
  func doSomething(request: MachineDetail.Something.Request)
}

protocol MachineDetailDataStore
{
  //var name: String { get set }
}

class MachineDetailInteractor: MachineDetailBusinessLogic, MachineDetailDataStore
{
  var presenter: MachineDetailPresentationLogic?
  var worker: MachineDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MachineDetail.Something.Request)
  {
    worker = MachineDetailWorker()
    worker?.doSomeWork()
    
    let response = MachineDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
