//
//  MachineDetailInteractor.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MachineDetailBusinessLogic
{
    func doSomething(machineId: String)
}

protocol MachineDetailDataStore
{
    var machineId: String! { get set}
    var displayMode: String? { get set}
}

class MachineDetailInteractor: MachineDetailBusinessLogic, MachineDetailDataStore
{
    
    var machineId: String!
    var displayMode: String?
    
    var presenter: MachineDetailPresentationLogic?
    var worker: MachineDetailWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(machineId: String)
    {
        worker = MachineDetailWorker()
        let machine = worker?.getData(machineId: machineId)
        
        presenter?.presentSomething(machine: machine!)
    }
}
