//
//  MachineDetailRouter.swift
//  Image Machine
//
//  Created by Juanita Vyatri on 24/11/18.
//  Copyright (c) 2018 Vyatri. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MachineDetailRoutingLogic
{
  func routeToEdit(machineId: String)
}

protocol MachineDetailDataPassing
{
  var dataStore: MachineDetailDataStore? { get }
}

class MachineDetailRouter: NSObject, MachineDetailRoutingLogic, MachineDetailDataPassing
{
  weak var viewController: MachineDetailViewController?
  var dataStore: MachineDetailDataStore?
  
  // MARK: Routing
  
  func routeToEdit(machineId: String)
  {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "MachineDetail") as! MachineDetailViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToEdit(source: dataStore!, destination: &destinationDS)
      navigateToEdit(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToEdit(source: MachineDetailViewController, destination: MachineDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToEdit(source: MachineDetailDataStore, destination: inout MachineDetailDataStore)
  {
    destination.machineId = source.machineId
    destination.displayMode = "edit"
  }
}
